# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_rts', [dirname(__file__)])
        except ImportError:
            import _rts
            return _rts
        if fp is not None:
            try:
                _mod = imp.load_module('_rts', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _rts = swig_import_helper()
    del swig_import_helper
else:
    import _rts
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def init():
  return _rts.init()
init = _rts.init

def read_config(*args):
  return _rts.read_config(*args)
read_config = _rts.read_config

def render():
  return _rts.render()
render = _rts.render

def listen_window():
  return _rts.listen_window()
listen_window = _rts.listen_window

def render_screen():
  return _rts.render_screen()
render_screen = _rts.render_screen
class MD3_Item(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, MD3_Item, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, MD3_Item, name)
    __repr__ = _swig_repr
    __swig_setmethods__["item"] = _rts.MD3_Item_item_set
    __swig_getmethods__["item"] = _rts.MD3_Item_item_get
    if _newclass:item = _swig_property(_rts.MD3_Item_item_get, _rts.MD3_Item_item_set)
    __swig_setmethods__["next"] = _rts.MD3_Item_next_set
    __swig_getmethods__["next"] = _rts.MD3_Item_next_get
    if _newclass:next = _swig_property(_rts.MD3_Item_next_get, _rts.MD3_Item_next_set)
    def __init__(self): 
        this = _rts.new_MD3_Item()
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _rts.delete_MD3_Item
    __del__ = lambda self : None;
MD3_Item_swigregister = _rts.MD3_Item_swigregister
MD3_Item_swigregister(MD3_Item)
cvar = _rts.cvar



